import { chromium, devices } from 'playwright';
import { startServer, findChromium, installCdnCache, CHROMIUM_ARGS, startGame } from './tools/birb-shot.mjs';
const { server, port } = await startServer(process.cwd());
const browser = await chromium.launch({ executablePath: findChromium(), args: CHROMIUM_ARGS });
const ctx = await browser.newContext({ ...devices['iPhone 13'], viewport:{width:390,height:844}, deviceScaleFactor:1 });
await installCdnCache(ctx);
const page = await ctx.newPage();
const warns=[]; page.on('console', m=>{ if(m.type()!=='log') warns.push(m.type()+': '+m.text().slice(0,180)); });
page.on('pageerror', e=>warns.push('PAGEERR: '+e.message));
await page.goto(`http://127.0.0.1:${port}/index.html?debug=1`, { waitUntil:'domcontentloaded' });
await startGame(page, 45000);
await page.waitForTimeout(1200);
console.log('before RR:', JSON.stringify(await page.evaluate(()=>window.__BIRB.modeState())));
await page.evaluate(()=>window.__BIRB.startMode('ring_rush'));
await page.waitForTimeout(2500);
console.log('after  RR:', JSON.stringify(await page.evaluate(()=>window.__BIRB.modeState())));
console.log('warnings:', warns.length?warns.slice(0,6):'none');
await browser.close(); server.close();
