// swift-tools-version:5.9
import PackageDescription

// Humanoid Creator — Phase 0 export gate.
//
// Everything in this package builds and tests on Linux with `swift test`.
// The iPad app target lives in ../app and is generated by XcodeGen; it depends
// on this package and contains the only Apple-framework code in the project.
//
// House rule: no simd / Metal / UIKit / CoreGraphics / ImageIO / CryptoKit /
// SwiftData imports anywhere in Sources/. See docs/humanoid-creator-validation/REPORT.md §5.1.
let package = Package(
    name: "Humanoid",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [
        .library(name: "HumanoidCore", targets: ["HumanoidCore"]),
        .library(name: "ExporterVRM", targets: ["ExporterVRM"]),
        .library(name: "ExporterFBX", targets: ["ExporterFBX"]),
    ],
    targets: [
        // zlib lives in both the Linux and iOS SDKs. A shim keeps the Swift side
        // free of C interop details and gives us real DEFLATE for PNG IDAT
        // (Foundation's .zlib emits RFC 1951 raw deflate, which PNG rejects).
        .target(name: "CZlibShim", linkerSettings: [.linkedLibrary("z")]),

        // The body template is a build artefact of tools/build_template.py, not
        // something the app can derive: bone-heat weighting is a sparse solve
        // over the whole mesh and its answer never changes. Shipped as a
        // resource so the tests and the iPad app read the identical bytes.
        .target(name: "HumanoidCore", dependencies: ["CZlibShim"],
                resources: [.copy("Resources/body-v1.bin")]),
        .target(name: "ExporterVRM", dependencies: ["HumanoidCore"]),

        // Vendored at pinned commits; see VENDORED.md beside each.
        .target(name: "UfbxWriteC", cSettings: [.headerSearchPath("include")]),
        .target(name: "UfbxC", cSettings: [.headerSearchPath("include")]),
        .target(name: "ExporterFBX", dependencies: ["HumanoidCore", "UfbxWriteC", "UfbxC"]),

        .executableTarget(name: "humanoid-cli", dependencies: ["HumanoidCore", "ExporterVRM", "ExporterFBX"]),

        .testTarget(name: "HumanoidCoreTests", dependencies: ["HumanoidCore"]),
        .testTarget(name: "ExporterVRMTests", dependencies: ["ExporterVRM", "HumanoidCore"]),
        .testTarget(name: "ExporterFBXTests", dependencies: ["ExporterFBX", "HumanoidCore"]),
    ]
)
